### ISSUE TITLE
CUDA out of memory error with ROCKET

### ISSUE THREAD

**Issue by maxmatical** [timeseriesAI/timeseriesAI#5]
I've been trying to use the ROCKET method to generate the random features, but for a much larger dataset, and I've been getting a CUDA out of memory error. Is there anyway to apply the transformation in batches, rather than loading the entire data into CUDA?

**Comment by oguiza** [comment]
Hi @maxmatical, 
Thanks for your question.
Yes, there is a way to create features for individual batches instead of the entire dataset.
Actually it's shown in nb 05, there's some code that does exactly that. 
I'm referring to these lines:
`model = ROCKET(data.features, data.seq_len, n_kernels=n_kernels,kss=kss).to(device)
        for j, (xb,yb) in enumerate(data.train_dl.new(shuffle=False, drop_last=False)):
            with torch.no_grad(): out = model(xb)
            X_train_tfm = out if j == 0 else torch.cat((X_train_tfm, out))`
The important thing there is to use the same model for all batches.
Please, let me know if you have any other question about this method.
